<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="ProjectGraph.fs"/>
        <Compile Include="SolutionDiscovery.fs"/>
        <Compile Include="ImplicitFiles.fs"/>
        <Compile Include="MirrorRoot.fs"/>
        <Compile Include="Hardlink.fs"/>
        <Compile Include="LinkStrategy.fs"/>
        <Compile Include="Materialize.fs"/>
        <Compile Include="SolutionFile.fs"/>
        <Compile Include="MsBuild.fs"/>
        <Compile Include="FileResolution.fs"/>
        <Compile Include="Pipeline.fs"/>
    </ItemGroup>

</Project>
