<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="ProjectGraph.fs"/>
        <Compile Include="SolutionDiscovery.fs"/>
        <Compile Include="MsBuild.fs"/>
        <Compile Include="FileResolution.fs"/>
    </ItemGroup>

</Project>
